TEAM_NAME = "Juventus FC"

# football-data.org competition codes (free tier)
COMPETITION_SERIE_A = "SA"
COMPETITION_CHAMPIONS_LEAGUE = "CL"
SUPPORTED_COMPETITIONS = [COMPETITION_SERIE_A, COMPETITION_CHAMPIONS_LEAGUE]

MATCH_STATUS_SCHEDULED = "SCHEDULED"
MATCH_STATUS_TIMED = "TIMED"
MATCH_STATUS_FINISHED = "FINISHED"
MATCH_STATUS_POSTPONED = "POSTPONED"

# football-data.org marks a fixture "SCHEDULED" until kickoff time is
# confirmed, then "TIMED" — both are still upcoming, not-yet-played matches.
UPCOMING_MATCH_STATUSES = (MATCH_STATUS_SCHEDULED, MATCH_STATUS_TIMED)

SOURCE_FOOTBALL_DATA = "football-data"
SOURCE_WIKIPEDIA = "wikipedia"
