TEAM_NAME = "Juventus FC"

# football-data.org competition codes (free tier)
COMPETITION_SERIE_A = "SA"
COMPETITION_CHAMPIONS_LEAGUE = "CL"
SUPPORTED_COMPETITIONS = [COMPETITION_SERIE_A, COMPETITION_CHAMPIONS_LEAGUE]

MATCH_STATUS_SCHEDULED = "SCHEDULED"
MATCH_STATUS_FINISHED = "FINISHED"
MATCH_STATUS_POSTPONED = "POSTPONED"

SOURCE_FOOTBALL_DATA = "football-data"
SOURCE_WIKIPEDIA = "wikipedia"
